### ISSUE TITLE
[simplism] excel style의 border 속성 적용 시 오류

### ISSUE THREAD

**Issue by sonaryu** [kslhunter/simplysm#14]
1. BorderTop 줌, 켜질때 오류안남
![캡처_2019_08_06_19_38_10_443](https://user-images.githubusercontent.com/43091039/62533517-d37d3180-b881-11e9-9647-d3179692d62d.png)

2.  BorderBottom줌, 켜질때 오류
![캡처_2019_08_06_19_40_03_648](https://user-images.githubusercontent.com/43091039/62533605-0b847480-b882-11e9-911e-5946a3d0aa02.png)

**Comment by kslhunter** [comment]
border 와 기타 속성을 어떤 순서로 넣느냐에 따라 오류 발생여부가 달라지는 듯함
