### ISSUE TITLE
사용안하는 함수 체크 오류

### ISSUE THREAD

**Issue by libu1129** [kslhunter/simplysm#36]
html에서 [disabled]="isUsable(item)"

했을 때

private isUsable(item: IItemVM): boolean{
return true;
}

같은 형식으로 선언해좋으면 isUsable 함수가 사용되지 않는다고 오류나며 watch가 안됩니다

**Comment by kslhunter** [comment]
정상입니다. 템플릿 코드와 기능코드는 별개코드로 public으로 선언해야 템플릿코드에서 접근 가능합니다
