### ISSUE TITLE
종종 watch-check가 무한대로 실행되는 현상 수정

### ISSUE THREAD

**Issue by kslhunter** [kslhunter/simplysm#4]
시간을 두고, 사라지는지 봐야함

**Comment by sonaryu** [comment]
db 수정 작업 중 watch-check 무한 루프 현상 발생

![캡처_2019_08_02_11_58_30_978](https://user-images.githubusercontent.com/43091039/62341116-0390a180-b51d-11e9-878b-6411041c29c6.png)

**Comment by kslhunter** [comment]
@sonaryu simplysm이랑 프로젝트랑 같이 켜고 한거임?
내가 simplysm을 publish를 안하고, 소스 수정후 푸쉬만해서 그런거일수 있으니..

**Comment by sonaryu** [comment]
@kslhunter 아마 그랬던거 같은데 확실하지는 않아요. 요즘은 simplysm 안키고 작업하고 있는데 저때이후로 아직까지는 같은 상황은 발생 안하고 있어요
